# Generated by Django 3.2.6 on 2021-08-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('erkak', 'male'), ('female', 'female')], max_length=6)),
                ('passport', models.CharField(max_length=255, unique=True)),
                ('telfon', models.CharField(max_length=255)),
                ('qayerga', models.CharField(choices=[('Qirgiziston', 'Qirgiziston'), ('Boshqa', 'Boshqa')], max_length=255)),
                ('test_olindi', models.DateTimeField()),
                ('natija_chiqdi', models.DateTimeField()),
                ('qrcode', models.ImageField(blank=True, upload_to='qrcode/')),
            ],
        ),
    ]
