# Generated by Django 3.2.6 on 2021-08-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210817_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_method', models.CharField(max_length=255)),
                ('name_of_labaratory', models.CharField(max_length=255)),
                ('head_of_labaratory', models.CharField(max_length=255)),
            ],
        ),
    ]
